version: '3.7'
services:
  dev:
    build:
      context: .
    hostname: dev
    volumes:
      - ./dottygen:/home/dev/dottygen
      - ./benchmark:/home/dev/benchmark
      - ./protocols:/home/dev/protocols
      - ./protocol_fsm:/home/dev/protocol_fsm
      - ./scripts:/home/dev/scripts
      - ./effpi_sandbox:/home/dev/effpi_sandbox
      - ./case_studies:/home/dev/case_studies
    ports: 
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8888:8888"

  test:
    build:
      context: .
    hostname: dev
    volumes:
      - ./dottygen:/home/dev/dottygen
      - ./effpi_sandbox:/home/dev/effpi_sandbox
      - ./case_studies:/home/dev/case_studies
    command: 
      python3.8 -m codegen.tests.system

volumes:
  benchmark:
  dottygen:
  protocols:
  protocol_fsm:
  scripts:
  effpi_sandbox:
  case_studies:
